import { Session } from "../../types";
import { palette } from "../../styles";

export const darkSide: Session = {
  sessionTitle: "the dark side of the moon",
  author: "pink floyd",
  id: "default",
  user: "default",
  tracks: [
    {
      title: "speak to me",
      parameters: [
        { parameter: "vocals", colour: "transparent", comment: "" },
        { parameter: "guitar", colour: "transparent", comment: "" },
        { parameter: "bass", colour: "transparent", comment: "" },
        {
          parameter: "percussion",
          colour: palette._blue,
          comment: "",
        },
        { parameter: "keys", colour: palette._grey, comment: "" },
        {
          parameter: "session musicians",
          colour: "transparent",
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._yellow, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "breathe (in the air)",
      parameters: [
        { parameter: "vocals", colour: palette._grey, comment: "" },
        { parameter: "guitar", colour: palette._yellow, comment: "" },
        { parameter: "bass", colour: palette._yellow, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._grey, comment: "" },
        {
          parameter: "session musicians",
          colour: "transparent",
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._grey, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "on the run",
      parameters: [
        { parameter: "vocals", colour: "transparent", comment: "nope" },
        { parameter: "guitar", colour: palette._grey, comment: "" },
        { parameter: "bass", colour: palette._yellow, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._yellow, comment: "" },
        {
          parameter: "session musicians",
          colour: palette._blue,
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._yellow, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "time",
      parameters: [
        { parameter: "vocals", colour: palette._yellow, comment: "" },
        { parameter: "guitar", colour: palette._yellow, comment: "" },
        { parameter: "bass", colour: palette._blue, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._grey, comment: "" },
        {
          parameter: "session musicians",
          colour: palette._yellow,
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._yellow, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "the great gig in the sky",
      parameters: [
        { parameter: "vocals", colour: "transparent", comment: "" },
        { parameter: "guitar", colour: palette._yellow, comment: "" },
        { parameter: "bass", colour: palette._blue, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._yellow, comment: "" },
        {
          parameter: "session musicians",
          colour: "transparent",
          comment: "",
        },
        {
          parameter: "guest vocals",
          colour: palette._blue,
          comment: "i believe the lyrics are `wow` ",
        },
        { parameter: "fx", colour: "transparent", comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "money",
      parameters: [
        { parameter: "vocals", colour: palette._grey, comment: "" },
        { parameter: "guitar", colour: palette._yellow, comment: "" },
        {
          parameter: "bass",
          colour: palette._yellow,
          comment: "dun daaa badum dun dun daaa dun",
        },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._grey, comment: "" },
        {
          parameter: "session musicians",
          colour: palette._grey,
          comment: "sax bruh",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._blue, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "us and them",
      parameters: [
        { parameter: "vocals", colour: palette._yellow, comment: "" },
        { parameter: "guitar", colour: palette._grey, comment: "" },
        { parameter: "bass", colour: palette._yellow, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._grey, comment: "" },
        {
          parameter: "session musicians",
          colour: palette._yellow,
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._yellow, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "any colour you like",
      parameters: [
        {
          parameter: "vocals",
          colour: palette._blue,
          comment: "i mean technically...",
        },
        { parameter: "guitar", colour: palette._grey, comment: "" },
        { parameter: "bass", colour: palette._grey, comment: "" },
        {
          parameter: "percussion",
          colour: palette._yellow,
          comment: "need to retrack this",
        },
        { parameter: "keys", colour: palette._blue, comment: "" },
        {
          parameter: "session musicians",
          colour: "transparent",
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._yellow, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "brain damage",
      parameters: [
        { parameter: "vocals", colour: palette._grey, comment: "" },
        { parameter: "guitar", colour: palette._yellow, comment: "" },
        { parameter: "bass", colour: palette._yellow, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._grey, comment: "" },
        {
          parameter: "session musicians",
          colour: palette._yellow,
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._blue, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        { parameter: "done", colour: palette._grey, comment: "" },
      ],
    },
    {
      title: "eclipse",
      parameters: [
        { parameter: "vocals", colour: palette._blue, comment: "" },
        { parameter: "guitar", colour: palette._grey, comment: "" },
        { parameter: "bass", colour: palette._blue, comment: "" },
        { parameter: "percussion", colour: palette._blue, comment: "" },
        { parameter: "keys", colour: palette._yellow, comment: "" },
        {
          parameter: "session musicians",
          colour: palette._grey,
          comment: "",
        },
        { parameter: "guest vocals", colour: "transparent", comment: "" },
        { parameter: "fx", colour: palette._grey, comment: "" },
        { parameter: "mix", colour: palette._grey, comment: "" },
        { parameter: "master", colour: palette._grey, comment: "" },
        {
          parameter: "done",
          colour: palette._grey,
          comment: "",
        },
      ],
    },
  ],
  parameters: [
    "title",
    "vocals",
    "guitar",
    "bass",
    "percussion",
    "keys",
    "session musicians",
    "guest vocals",
    "fx",
    "mix",
    "master",
    "done",
  ],
};
