export const palette = {
  _blue: "#7284A8",
  _yellow: "#F2BF80",
  _red: "#D93D1A",
  _black: "#272727",
  _darkgrey: "#707070",
  _grey: "#2D2D2D",
  _white: "#F3EFE0",
};

export const styles = {
  // LOGO
  logoSx: {
    fontFamily: "Noto-Serif",
    textTransform: "lowercase",
    userSelect: "none",
    msUserSelect: "none",
    webkitTouchCallout: "none",
    webkitUserSelect: "none",
    khtmlUserSelectNone: "none",
    mozUserSelectNone: "none",
    msUserSelectNone: "none",
    userSelectNone: "none",
    nav: {
      fontFamily: "Noto-Serif",
      textDecoration: "none",
      color: palette._blue,
      fontSize: "2.5vw",
    },
    modal: {
      fontFamily: "Noto-Serif",
      textTransform: "lowercase",
      userSelect: "none",
      msUserSelect: "none",
      webkitTouchCallout: "none",
      webkitUserSelect: "none",
      khtmlUserSelectNone: "none",
      mozUserSelectNone: "none",
      msUserSelectNone: "none",
      userSelectNone: "none",
      color: palette._blue,
      fontSize: "3vw",
      mb: "0.25vw",
    },
    main: {
      fontFamily: "Noto-Serif",
      textTransform: "lowercase",
      userSelect: "none",
      msUserSelect: "none",
      webkitTouchCallout: "none",
      webkitUserSelect: "none",
      khtmlUserSelectNone: "none",
      mozUserSelectNone: "none",
      msUserSelectNone: "none",
      userSelectNone: "none",
      display: "flex",
      alignContent: "center",
      justifyContent: "center",
      color: palette._blue,
      fontSize: "13vw",
      mt: "-5vh",
    },
  },
};
